sudo: required
dist: trusty
language: cpp
compiler: gcc
env:
- QT="qt4"
- QT="qt5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev qt4-qmake qt5-qmake qtbase5-dev
script:
  - mkdir build
  - cd build
  - qmake qt=${QT} -v
  - qmake qt=${QT} ..
  - make
