sudo: required
dist: trusty
language: cpp
compiler: gcc
env:
- QT=4
- QT=5
install:
  - sudo apt-get update -qq
  - if [ "$QT" = "4" ]; then sudo apt-get install -qq libqt4-dev qt4-qmake qt4-default; fi
  - if [ "$QT" = "5" ]; then sudo apt-get install -qq qtbase5-dev qt5-qmake qt5-default; fi
script:
  - mkdir build
  - cd build
  - qmake -v
  - qmake ..
  - make
